- name: Teardown everything
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Basic deployment
      terraform:
        project_path: 03-deploy-apps/
        state: absent
      tags:
        - apps

    - name: Teardown cluster
      terraform:
        project_path: 02-test-cluster/
        state: absent
      tags:
        - cluster
        
    - name: Teardown Rancher server
      terraform:
        project_path: 01-rancher-server/
        state: absent
      tags:
        - rancher
