apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  labels:
{{ include "traefik.labels" . | indent 4 }}

data:
  traefik.yaml: |
    global:
      sendAnonymousUsage: true
    api:
      insecure: true
      {{- if .Values.dashboard.enabled }}
      dashboard: true
      {{- end }}
    ping: {} # Enable with defaults
    metrics:
      prometheus: {} # Enable with defaults
    #  influxDB:
    #    address: localhost:8089
    #    protocol: udp
    log:
      level: INFO
    accessLog: {} # Enable with defaults
    entryPoints:
      web:
        address: :80
      websecure:
        address: :443
    forwardedHeaders:
      insecure: true
    providers:
      kubernetesCRD:
        ingressClass: traefik
        namespaces: [] # All namespaces
      kubernetesIngress:
        ingressClass: traefik
        namespaces: [] # All namespaces
    certificatesResolvers:
      default:
        acme:
          storage: /acme/acme.json
          {{- if .Values.acme.staging }}
          caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
          {{- end }}
          {{- if eq .Values.acme.challengeType "dns-01" }}
          dnsChallenge:
            provider: {{ .Values.acme.dnsProvider.name | quote }}
            {{- if .Values.acme.delayBeforeCheck }}
            delayBeforeCheck: {{ .Values.acme.delayBeforeCheck }}
            {{- end }}
            {{- with .Values.acme.resolvers }}
            resolvers:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- end }}
    tls:
      options:
        default:
          minVersion: VersionTLS12
