#{{- if semverCompare "^1.16-0" .Capabilities.KubeVersion.GitVersion }}
#apiVersion: apiextensions.k8s.io/v1
#{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
#{{- end }}
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
  labels:
{{ include "traefikv2.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": crd-install

spec:
  group: traefik.containo.us
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced

---
#{{- if semverCompare "^1.16-0" .Capabilities.KubeVersion.GitVersion }}
#apiVersion: apiextensions.k8s.io/v1
#{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
#{{- end }}
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us
  labels:
{{ include "traefikv2.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": crd-install
    
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced

---
#{{- if semverCompare "^1.16-0" .Capabilities.KubeVersion.GitVersion }}
#apiVersion: apiextensions.k8s.io/v1
#{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
#{{- end }}
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
  labels:
{{ include "traefikv2.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": crd-install
    
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: Middleware
    plural: middlewares
    singular: middleware
  scope: Namespaced

---
#{{- if semverCompare "^1.16-0" .Capabilities.KubeVersion.GitVersion }}
#apiVersion: apiextensions.k8s.io/v1
#{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
#{{- end }}
kind: CustomResourceDefinition
metadata:
  name: tlsoptions.traefik.containo.us
  labels:
{{ include "traefikv2.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": crd-install
    
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: TLSOption
    plural: tlsoptions
    singular: tlsoption
  scope: Namespaced
