apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: traefik
  labels:
    app: traefik
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
          env:
          {{- range $k, $v := (index .Values.acme.dnsProvider .Values.acme.dnsProvider.name) }}
            {{- if or $v $.Values.acme.dnsProvider.existingSecretName }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                {{- if $.Values.acme.dnsProvider.existingSecretName }}
                  name: {{ $.Values.acme.dnsProvider.existingSecretName }}
                {{- else }}
                  name: {{ template "traefikv2.fullname" $ }}-dnsprovider-config
                {{- end }}
                  key: {{ $k }}
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
            {{ toYaml .Values.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/traefik
            - name: acme
              mountPath: /acme/acme.json
      volumes:
      - name: config-volume
        configMap:
          name: traefik-config
      {{- if .Values.acme.enabled }}
      - name: acme
        {{- if .Values.acme.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.acme.persistence.existingClaim | default (printf "%s-acme" (include "traefikv2.fullname" .)) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- end }}