- name: Install required modules
  pip:
    name: openshift>=0.6
    state: latest

- name: Deploy cert-manager
  k8s:
    namespace: "{{ cert_mananger_namespace }}"
    state: present
    definition: "{{ item }}"
  loop: "{{ lookup('url', 'https://github.com/jetstack/cert-manager/releases/download/v{{ cert_mananger_version }}/cert-manager.yaml', split_lines=False) | from_yaml_all | select('ne', None) | list }}"

- name: Deploy Cloudflare API secret
  k8s:
    namespace: "{{ cert_mananger_namespace }}"
    state: present
    definition: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-key
      type: Opaque
      data:
        api-key: "{{ cloudflare_api_key | b64encode }}"

- name: Deploy staging issuer
  k8s:
    namespace: "{{ cert_mananger_namespace }}"
    state: present
    definition: |-
      apiVersion: cert-manager.io/v1alpha2
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-staging
      spec:
        acme:
          email: "{{ acme_account_email }}"
          server: "{{ acme_ca_server_staging }}"
          privateKeySecretRef:
            name: staging-issuer-account-key
          solvers:
            - dns01:
                cloudflare:
                  email: "{{ cloudflare_api_email }}"
                  apiKeySecretRef:
                      name: cloudflare-api-key
                      key: api-key

- name: Deploy production issuer
  k8s:
    namespace: "{{ cert_mananger_namespace }}"
    state: present
    definition: |-
      apiVersion: cert-manager.io/v1alpha2
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-production
      spec:
        acme:
          email: "{{ acme_account_email }}"
          server: "{{ acme_ca_server_production }}"
          privateKeySecretRef:
            name: production-issuer-account-key
          solvers:
            - dns01:
                cloudflare:
                  email: "{{ cloudflare_api_email }}"
                  apiKeySecretRef:
                      name: cloudflare-api-key
                      key: api-key