#cloud-config
hostname: ${hostname}
ssh_authorized_keys:
%{ for ssh_key in split(",", extra_ssh_keys) ~}
  - ${ssh_key}
%{ endfor ~}  

write_files:
  - path: /opt/rancher/bin/start.sh
    permissions: "0700"
    owner: root
    content: |
      #!/bin/bash
      echo y | ros install -f -c /cloud-config.yml -d /dev/sda

  - path: /cloud-config.yml
    permissions: "0600"
    owner: root
    content: |
      #cloud-config
      hostname: ${hostname}
      ssh_authorized_keys:
        - ${rancher_ssh_key}
%{ for ssh_key in split(",", extra_ssh_keys) ~}
        - ${ssh_key}
%{ endfor ~}  
      rancher:
        bootstrap_docker:
          registry_mirror: "https://${docker_registry}"
        docker:
          registry_mirror: "https://${docker_registry}"
        system_docker:
          registry_mirror: "https://${docker_registry}"
        services_include:
          kernel-extras: true
          volume-nfs: true
        network:
          dns:
            nameservers:
%{ for address in split(",", dns_servers) ~}
              - ${address}
%{ endfor ~}
            search:
              - ${dns_domain}
          interfaces:
            eth0:
              dhcp: false
              address: ${address_cidr_ipv4}
              gateway: ${gateway_ipv4}
              mtu: 1500
            eth1:
              dhcp: true
              mtu: 9000
